apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-task-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        app: nodejs  
    spec:                       
      containers: 
      - name: node-js 
        image:node-js-image:v1 # image we pushed
        ports:
        - containerPort: 3000
 env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always